/// Core authentication logic for `__check_auth`.
///
/// This module orchestrates the entire authentication pipeline:
/// 1. Nonce verification & replay protection
/// 2. Signer lookup
/// 3. Cryptographic signature verification (secp256r1 or ed25519)
/// 4. Session key scope validation (if applicable)
/// 5. Policy enforcement (spending limits)
/// 6. TTL piggyback refresh for critical storage entries

use soroban_sdk::{
    auth::Context,
    crypto::Hash,
    Env, Vec,
};

use novus_types::{SignerType, WalletError, WalletSignature};

use crate::nonce;
use crate::policy;
use crate::session;
use crate::storage::Storage;
use crate::webauthn;

/// Main authentication entry point, called from `CustomAccountInterface::__check_auth`.
///
/// # Arguments
/// * `env` - Soroban execution environment
/// * `signature_payload` - Hash of the authorization payload generated by the runtime
/// * `signature` - Custom WalletSignature containing credential_id, sig bytes, nonce, etc.
/// * `auth_contexts` - List of contract invocations being authorized
///
/// # Returns
/// * `Ok(())` - Authentication and all policy checks passed
/// * `Err(WalletError)` - Specific error describing the failure
pub fn check_auth(
    env: &Env,
    signature_payload: &Hash<32>,
    signature: &WalletSignature,
    auth_contexts: &Vec<Context>,
) -> Result<(), WalletError> {
    // ──────────────────────────────────────────────────────────────
    // STEP 1: Replay Protection (Nonce + Payload Hash Guard)
    // ──────────────────────────────────────────────────────────────
    nonce::verify_and_increment_nonce(env, signature, signature_payload)?;

    // ──────────────────────────────────────────────────────────────
    // STEP 2: Signer Lookup
    // ──────────────────────────────────────────────────────────────
    let signer = Storage::get_signer(env, &signature.credential_id)?;

    // ──────────────────────────────────────────────────────────────
    // STEP 3: Cryptographic Signature Verification
    // ──────────────────────────────────────────────────────────────
    match signer.signer_type {
        SignerType::Passkey => {
            // WebAuthn secp256r1 verification using Protocol 21 host function.
            // Reconstructs the WebAuthn signed message from authenticator_data
            // and client_data_json_hash, then verifies against the stored pubkey.
            webauthn::verify_passkey_signature(env, &signer.public_key, signature);
        }

        SignerType::Ed25519 => {
            // Standard ed25519 verification against the signature payload.
            webauthn::verify_ed25519_signature(
                env,
                &signer.public_key,
                signature_payload,
                &signature.signature_bytes,
            );
        }

        SignerType::SessionKey => {
            // Session keys use ed25519 for signatures...
            webauthn::verify_ed25519_signature(
                env,
                &signer.public_key,
                signature_payload,
                &signature.signature_bytes,
            );

            // ...but also require scope validation (whitelists, spending caps)
            session::verify_session_scope(
                env,
                &signer.credential_id,
                auth_contexts,
            )?;

            // Session keys skip general policy enforcement
            // (they have their own, more restrictive policies)
            // Still refresh TTLs before returning
            refresh_ttls(env, &signature.credential_id);

            return Ok(());
        }

        SignerType::Guardian => {
            // Guardians CANNOT authorize normal transactions.
            // They can only participate in recovery proposals
            // (handled by the RecoveryModule contract).
            return Err(WalletError::InvalidAuthContext);
        }
    }

    // ──────────────────────────────────────────────────────────────
    // STEP 4: Policy Enforcement (for Passkey and Ed25519 signers)
    // ──────────────────────────────────────────────────────────────
    policy::enforce_policies(env, auth_contexts)?;

    // ──────────────────────────────────────────────────────────────
    // STEP 5: Piggyback TTL Refresh
    // ──────────────────────────────────────────────────────────────
    refresh_ttls(env, &signature.credential_id);

    Ok(())
}

/// Piggyback TTL refresh for critical storage entries.
///
/// Called during every successful __check_auth to ensure critical data
/// never gets archived. This is the "heartbeat" that keeps the account alive.
fn refresh_ttls(env: &Env, credential_id: &soroban_sdk::BytesN<32>) {
    // Refresh Instance storage (config + initialized flag)
    Storage::extend_instance_ttl(env);

    // Refresh the signer entry used for this auth
    Storage::bump_signer_ttl(env, credential_id);
}
